{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2017-14503",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "libarchive 3.3.2 suffers from an out-of-bounds read within lha_read_data_none() in archive_read_support_format_lha.c when extracting a specially crafted lha archive, related to lha_crc16."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "https://github.com/libarchive/libarchive/issues/948",
                "refsource": "MISC",
                "url": "https://github.com/libarchive/libarchive/issues/948"
            },
            {
                "name": "USN-3736-1",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3736-1/"
            },
            {
                "name": "https://bugs.debian.org/875960",
                "refsource": "MISC",
                "url": "https://bugs.debian.org/875960"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2018-20c24949c0",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QAHTQQHWOKYDFRYOU5GWTJVHWQNV32FQ/"
            }
        ]
    }
}